# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
# It will also deploy the build to two different repos with https://github.com/peaceiris/actions-gh-pages

name: Build Site

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [13.14.0]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - run: npm ci
        working-directory: ./web
      - run: npm run check-format
        working-directory: ./web
      - run: npm run lint
        working-directory: ./web
      - run: npm run test
        working-directory: ./web
      - run: npm run build
        working-directory: ./web
      - name: Save build output
        uses: actions/upload-artifact@v1
        with:
          name: built-output
          path: ./web/dist
    env:
      NODE_OPTIONS: '--max-old-space-size=4096'

  deploy-imjoy:
    runs-on: ubuntu-latest
    needs: build
    # if: github.ref == 'refs/heads/master'
    steps:
      # - name: Load saved build output
      #   uses: actions/download-artifact@v1
      #   with:
      #     name: built-output
      #     path: ./web/dist
      # - name: Deploy ImJoy to https://imjoy.io
      #   uses: peaceiris/actions-gh-pages@v3.5.0
      #   with:
      #     deploy_key: ${{ secrets.ACTION_DEPLOY_KEY }}
      #     publish_dir: ./web/dist
      #     commit_message: Deploy to GitHub Pages
      - name: Tag the repo if version has been updated
        uses: oeway/npm-publish-action@1.1.3
        with:
          tag_name: "v%s"
          tag_message: "v%s"
          commit_pattern: "^Release (\\S+)"
          commit_user: oeway
          publish_with: skip
        env:
          GITHUB_WORKSPACE: ./web
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
